### ISSUE TITLE
Format of input data from multiple individuals

### ISSUE THREAD

**Issue by samfenske** [amitfrish/TimeAx#1]
Great work! I'm trying to see if I could apply this to some of our own data, and have a question in terms of how to feed input data from multiple individuals. It appears that the example dataset is from one individual, with 27 samples at different time points. How would I structure input data from multiple individuals, would I just merge the data to the same matrix?

**Comment by samfenske** [comment]
I think I figured it out- I hadn't seen the UBCSamples variable that encodes which columns belong to which individuals. I'm assuming these are ordered in chronological order from left to right (ex. if samples 22-25 are from patient 5, then sample 22 would be the first time point and 25 the last).

**Comment by amitfrish** [comment]
Hey Sam,
I'm happy that you liked the idea and the method.
You are right, the UBCSamples is the id vector used to signal the algorithm which sample came from which patient. TimeAx assumes that the order of samples in the data (within each patient) is based on the chronological time so the first sample of patient 5 will be the first time point, the second will be the second time point and so on.
To be clear, the example data is just a scrambled data so there should be no actual biological effect there but this is the way to run the method.
If you have any more questions, please let me know and good luck with your analysis.

Amit
